/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menus.java
 *
 * Created on Feb 24, 2009, 10:04:59 PM
 */
package edu.uml.cs.GUIProgramming.jjmccaul;

import edu.uml.cs.GUIProgramming.MusicComp.*;

/**
 * This class contains the code to generate the application menus.
 * @author Jesse M. Heines, UMass Lowell Computer Science
 * @author <a href="mailto:heines@cs.uml.edu">heines@cs.uml.edu</a>
 * @version 1.0, February 24, 2009
 * Copyright &copy; 2009 by Jesse M. Heines.  All rights reserved.  May be freely
 *     copied or excerpted for educational purposes with credit to the author.
 */
public class Menus extends javax.swing.JFrame {

  /** the following is required to keep NetBeans happy */
  static final long serialVersionUID = 0 ;

  /** The main application for reference within this class. */
  Main mainApp = null;

  /** Creates new form Menus */
  public Menus() {
    initComponents();
  }

  /**
   * Call this constructor from the Main application to initialize the class level mainApp object.
   * @param mainApp the main application for reference within this class
   */
  public Menus( Main mainApp ) {
    this();   // call the default constructor, which must always be called first
    this.mainApp = mainApp;   // save the reference to the Main application
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menubarMain = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    menuitemExit = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    menuFile.setText("File");

    menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
    menuitemExit.setText("Exit");
    menuitemExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuitemExitActionPerformed(evt);
      }
    });
    menuFile.add(menuitemExit);

    menubarMain.add(menuFile);

    setJMenuBar(menubarMain);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Action handler for the File menu Exit item.
   * @param evt a standard Java ActionEvent
   */
    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
      if ( mainApp != null ) {
        mainApp.btnExitActionPerformed();   // note call to method in Main class
      } else {
        System.exit( 0 );
      }
    }//GEN-LAST:event_menuitemExitActionPerformed

  /**
   * Add menus to the main application.  
   * <p>All of this code is copied directly from the NetBeans-generated code above.
   * The only change is in the last line, where the constructed menu is added to the
   * mainApp object, which was initialized in the one-parameter constructor, rather
   * than "this" (the JFrame for the Menus class).<p>
   */
  public void addMainMenus() {
    menubarMain = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    menuitemExit = new javax.swing.JMenuItem();

    setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

    menuFile.setText( "File" );

    menuitemExit.setAccelerator( javax.swing.KeyStroke.getKeyStroke( java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK ) );
    menuitemExit.setText( "Exit" );
    menuitemExit.addActionListener( new java.awt.event.ActionListener() {
      public void actionPerformed( java.awt.event.ActionEvent evt ) {
        menuitemExitActionPerformed( evt );
      }
    } );
    menuFile.add( menuitemExit );

    menubarMain.add( menuFile );

    // note the specification of the main application JFrame object
    mainApp.setJMenuBar( menubarMain );
  }

  /**
   * The standard Java main method.
   * @param args the command line arguments
   */
  public static void main( String args[] ) {
    java.awt.EventQueue.invokeLater( new Runnable() {

      public void run() {
        new Menus().setVisible( true );
      }
    } );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  /** the File menu on the main applicatoin menu bar */
  private javax.swing.JMenu menuFile;
  /** the main application menu bar */
  private javax.swing.JMenuBar menubarMain;
  /** the Exit menu item on the File menu */
  private javax.swing.JMenuItem menuitemExit;
  // End of variables declaration//GEN-END:variables
}
