/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menus.java
 *
 * Created on Feb 24, 2009, 10:04:59 PM
 */
package edu.uml.cs.GUIProgramming.jjmccaul;

import edu.uml.cs.GUIProgramming.MusicComp.*;
import javax.swing.JFrame;

/**
 * This class contains the code to generate the application menus.
 * @author Jesse M. Heines, UMass Lowell Computer Science
 * @author <a href="mailto:heines@cs.uml.edu">heines@cs.uml.edu</a>
 * @version 1.0, February 24, 2009
 * Copyright &copy; 2009 by Jesse M. Heines.  All rights reserved.  May be freely
 *     copied or excerpted for educational purposes with credit to the author.
 */
public class Menus extends javax.swing.JFrame {

  /** the following is required to keep NetBeans happy */
  static final long serialVersionUID = 0 ;

  /** The main application for reference within this class. */
  Main mainApp = null;

  /** Creates new form Menus */
  public Menus() {
    initComponents();
  }

  /**
   * Call this constructor from the Main application to initialize the class level mainApp object.
   * @param mainApp the main application for reference within this class
   */
  public Menus( Main mainApp ) {
    this();   // call the default constructor, which must always be called first
    this.mainApp = mainApp;   // save the reference to the Main application
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings( "unchecked" )
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    menubarMain = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    jSeparator1 = new javax.swing.JSeparator();
    menuitemExit = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    menuFile.setText("File");

    jMenuItem1.setText("jMenuItem1");
    menuFile.add(jMenuItem1);

    jMenuItem2.setText("jMenuItem2");
    menuFile.add(jMenuItem2);

    jMenuItem3.setText("jMenuItem3");
    menuFile.add(jMenuItem3);
    menuFile.add(jSeparator1);

    menuitemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
    menuitemExit.setText("Exit");
    menuitemExit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuitemExitActionPerformed(evt);
      }
    });
    menuFile.add(menuitemExit);

    menubarMain.add(menuFile);

    setJMenuBar(menubarMain);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * Action handler for the File menu Exit item.
   * @param evt a standard Java ActionEvent
   */
    private void menuitemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemExitActionPerformed
      if ( mainApp != null ) {
        mainApp.btnExitActionPerformed();   // note call to method in Main class
      } else {
        System.exit( 0 );
      }
    }//GEN-LAST:event_menuitemExitActionPerformed

  /**
   * This method is intended to be called from other classes.
   * @param jfrm
   */
  public void attachMenubar( JFrame jfrm ) {
    jfrm.setJMenuBar( menubarMain );
  }


  /**
   * The standard Java main method.
   * @param args the command line arguments
   */
  public static void main( String args[] ) {
    java.awt.EventQueue.invokeLater( new Runnable() {

      public void run() {
        new Menus().setVisible( true );
      }
    } );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JSeparator jSeparator1;
  /** the File menu on the main applicatoin menu bar */
  private javax.swing.JMenu menuFile;
  /** the main application menu bar */
  private javax.swing.JMenuBar menubarMain;
  /** the Exit menu item on the File menu */
  private javax.swing.JMenuItem menuitemExit;
  // End of variables declaration//GEN-END:variables
}
