/*
 * SaveLoadDemo.java
 *
 * Created on Mar 12, 2009, 8:41:51 AM
 */

package edu.uml.cs.GUIProgramming.rcaisse;

import javax.swing.UIManager; // Needed for "look and feel"

/**
 *
 * This is a simple program to show saving and loading.
 *
 * @author  Ross Caisse, UMass Lowell Computer Science, <a href="mailto:rcaisse@gmail.com">rcaisse@gmail.com</a>
 * @version 1.0, 2009-3-01
 */
public class SaveLoadDemo extends javax.swing.JFrame {

    // This is the entire compostion of notes
    public MusicComposition myComp;

    /** Creates new form SaveLoadDemo */
    public SaveLoadDemo() {
        // set the LookAndFeel to match the IDE
        // reference: Robinson & Vorobiev p. 728
        UIManager.LookAndFeelInfo[] info =
            UIManager.getInstalledLookAndFeels();
        // default installed LookAndFeels
        // 0: javax.swing.plaf.metal.MetalLookAndFeel (default)
        // 1: com.sun.java.swing.plaf.motif.MotifLookAndFeel
        // 2: com.sun.java.swing.plaf.windows.WindowsLookAndFeel
        // 3: com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel
        int lafno = 2;   // desired LookAndFeel for Windows XP
        try {
          UIManager.setLookAndFeel( info[lafno].getClassName() );
        } catch ( Exception e ) {
          System.out.println( "Couldn't load " + info[lafno].getClassName() +
              " look and feel " + e );
          System.exit( 1 );  // abort run
        }

        initComponents();

        // Set the size of the frame
        this.setSize(600,600);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnDeleteNote = new javax.swing.JButton();
        jbtnAddNote = new javax.swing.JButton();
        jbtnLoad = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaMsg = new javax.swing.JTextArea();
        jlblX = new javax.swing.JLabel();
        jlblY = new javax.swing.JLabel();
        jlblHeight = new javax.swing.JLabel();
        jlblWidth = new javax.swing.JLabel();
        jlblShape = new javax.swing.JLabel();
        jtxtX = new javax.swing.JTextField();
        jtxtY = new javax.swing.JTextField();
        jtxtHeight = new javax.swing.JTextField();
        jtxtWidth = new javax.swing.JTextField();
        jtxtShape = new javax.swing.JTextField();
        jlblNote = new javax.swing.JLabel();
        jtxtNoteToDelete = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Save/Load Demo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnDeleteNote.setText("Delete Note");
        jbtnDeleteNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteNoteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDeleteNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 290, 100, -1));

        jbtnAddNote.setText("Add Note");
        jbtnAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNoteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnAddNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jbtnLoad.setText("Load");
        jbtnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoadActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jtxaMsg.setColumns(20);
        jtxaMsg.setRows(5);
        jScrollPane1.setViewportView(jtxaMsg);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 310, 460));

        jlblX.setText("X-Coor");
        getContentPane().add(jlblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jlblY.setText("Y-Coor");
        getContentPane().add(jlblY, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jlblHeight.setText("Height");
        getContentPane().add(jlblHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jlblWidth.setText("Width");
        getContentPane().add(jlblWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jlblShape.setText("Shape");
        getContentPane().add(jlblShape, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        getContentPane().add(jtxtX, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, -1));
        getContentPane().add(jtxtY, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, -1));
        getContentPane().add(jtxtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, -1));
        getContentPane().add(jtxtWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 80, -1));
        getContentPane().add(jtxtShape, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, -1));

        jlblNote.setText("Note #");
        getContentPane().add(jlblNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));
        getContentPane().add(jtxtNoteToDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 60, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // Save the composition to a file
        SaveAndLoad.SaveComposition(myComp);
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoadActionPerformed
        // Load the composition
        myComp = SaveAndLoad.LoadComposition();

        // Print the note information into the text area
        jtxaMsg.setText("");
        jtxaMsg.setText(myComp.toString());
    }//GEN-LAST:event_jbtnLoadActionPerformed

    private void jbtnDeleteNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteNoteActionPerformed
        myComp.deleteNote(Integer.parseInt(jtxtNoteToDelete.getText()));

        // Print the note information into the text area
        jtxaMsg.setText("");
        jtxaMsg.setText(myComp.toString());

        jtxtNoteToDelete.setText("");
    }//GEN-LAST:event_jbtnDeleteNoteActionPerformed

    private void jbtnAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNoteActionPerformed
        myComp.addNote(new MusicNote(Integer.parseInt(jtxtX.getText()),
                Integer.parseInt(jtxtY.getText()), Integer.parseInt(jtxtHeight.getText()),
                Integer.parseInt(jtxtWidth.getText()),
                jtxtShape.getText()));

        // Print the note information into the text area
        jtxaMsg.setText("");
        jtxaMsg.setText(myComp.toString());

        jtxtX.setText("");
        jtxtY.setText("");
        jtxtShape.setText("");
        jtxtHeight.setText("");
        jtxtWidth.setText("");
    }//GEN-LAST:event_jbtnAddNoteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveLoadDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAddNote;
    private javax.swing.JButton jbtnDeleteNote;
    private javax.swing.JButton jbtnLoad;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JLabel jlblHeight;
    private javax.swing.JLabel jlblNote;
    private javax.swing.JLabel jlblShape;
    private javax.swing.JLabel jlblWidth;
    private javax.swing.JLabel jlblX;
    private javax.swing.JLabel jlblY;
    private javax.swing.JTextArea jtxaMsg;
    private javax.swing.JTextField jtxtHeight;
    private javax.swing.JTextField jtxtNoteToDelete;
    private javax.swing.JTextField jtxtShape;
    private javax.swing.JTextField jtxtWidth;
    private javax.swing.JTextField jtxtX;
    private javax.swing.JTextField jtxtY;
    // End of variables declaration//GEN-END:variables

}
