/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JTL_WindowSize.java
 *
 * Created on Mar 2, 2009, 12:59:09 PM
 */

package edu.uml.cs.GUIProgramming.jtlucas;

import edu.uml.cs.GUIProgramming.MusicComp.*;
import javax.swing.*;

/**
 *
 * @author JTLucas
 */
public class JTL_WindowSize extends javax.swing.JFrame {

    /** the following is required to keep NetBeans happy */
    static final long serialVersionUID = 0 ;

    /** The main application for reference within this class. */
    Main mainApp = null;

    /** Creates new form JTL_WindowSize */
    public JTL_WindowSize() {
        initComponents();
    }

    /**
    * Call this constructor from the Main application to initialize the class level mainApp object.
    * @param mainApp the main application for reference within this class
    */
    public JTL_WindowSize( Main mainApp ) {
      this();   // call the default constructor, which must always be called first
      this.mainApp = mainApp;   // save the reference to the Main application
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setMinimumSize(new java.awt.Dimension(800, 700));

    jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
    jScrollPane1.setMaximumSize(new java.awt.Dimension(800, 530));
    jScrollPane1.setMinimumSize(new java.awt.Dimension(800, 530));
    jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 530));

    jPanel1.setMaximumSize(new java.awt.Dimension(3000, 508));
    jPanel1.setMinimumSize(new java.awt.Dimension(3000, 508));
    jPanel1.setPreferredSize(new java.awt.Dimension(3000, 508));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 3000, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 511, Short.MAX_VALUE)
    );

    jScrollPane1.setViewportView(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(170, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

     /**
     * This method is intended to be called from other classes.
     * To set the window sizes to those that were chosen by Jesse L.
     * @param jfrm
     */
     public void setWindowSize( JFrame jfrm ) {
       jfrm.setMinimumSize(new java.awt.Dimension(800, 700) );
     }

     /**
     * This method is intended to be called from other classes.
     * To set the scroll panel sizes to those that were chosen by Jesse L.
     * @param jspane
     */
     public void setScrollPaneSize( JScrollPane jspane ) {
       //Set all jscroll pane sizes to be Width = 800, Height = 530.
       jspane.setMinimumSize(new java.awt.Dimension(800, 530));
       jspane.setMaximumSize(new java.awt.Dimension(800, 530));
       jspane.setPreferredSize(new java.awt.Dimension(800, 530));
     }

     /**
     * This method is intended to be called from other classes.
     * To set the panel sizes to those that were chosen by Jesse L.
     * @param jpanel
     */
     public void setPanelSize( JPanel jpanel ) {
       //Set all jpanel sizes to be Width = 3000, Height = 508.
       jpanel.setMinimumSize(new java.awt.Dimension(3000, 508));
       jpanel.setMaximumSize(new java.awt.Dimension(3000, 508));
       jpanel.setPreferredSize(new java.awt.Dimension(3000, 508));
     }

     /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTL_WindowSize().setVisible(true);
            }
        });
     }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables

}
