/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ShapeDemo.java
 *
 * Created on Feb 19, 2009, 2:02:19 AM
 */

package edu.uml.cs.GUIProgramming.ngilbert.shapedemo;

import java.awt.Dimension;

/**
 *
 * @author Nathan
 */
public class ShapeDemo extends javax.swing.JFrame {

    /** Creates new form ShapeDemo */
    public ShapeDemo() {
        initComponents();
        //canvas1.setSize(new Dimension(1000,1000));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    canvas1 = new edu.uml.cs.GUIProgramming.ngilbert.shapedemo.Canvas();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jScrollPane1.setInheritsPopupMenu(true);

    javax.swing.GroupLayout canvas1Layout = new javax.swing.GroupLayout(canvas1);
    canvas1.setLayout(canvas1Layout);
    canvas1Layout.setHorizontalGroup(
      canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 419, Short.MAX_VALUE)
    );
    canvas1Layout.setVerticalGroup(
      canvas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 310, Short.MAX_VALUE)
    );

    jScrollPane1.setViewportView(canvas1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeDemo().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private edu.uml.cs.GUIProgramming.ngilbert.shapedemo.Canvas canvas1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
