/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on Feb 24, 2009, 2:29:19 PM
 */
package edu.uml.cs.GUIProgramming.MusicComp;

import edu.uml.cs.GUIProgramming.heines.*;
import edu.uml.cs.GUIProgramming.jjmccaul.*;
import edu.uml.cs.GUIProgramming.jtlucas.*;
import edu.uml.cs.GUIProgramming.jstarman.*; 
import edu.uml.cs.GUIProgramming.jebert.*;
import edu.uml.cs.GUIProgramming.plaidler.*;
import edu.uml.cs.GUIProgramming.etran.*;


/**
 * This is the main driver for the entire music composition program.
 * @author Jesse M. Heines, UMass Lowell Computer Science
 * @author <a href="mailto:heines@cs.uml.edu">heines@cs.uml.edu</a>
 * @version 1.0, February 24, 2009
 * Copyright &copy; 2009 by Jesse M. Heines.  All rights reserved.  May be freely
 *     copied or excerpted for educational purposes with credit to the author.
 */
public class Main extends javax.swing.JFrame {

  /** the following is required to keep NetBeans happy */
  static final long serialVersionUID = 0 ;

  /** the Menus object in package jjmccaul by James */
  Menus menus;

  /** the WindowSize object in package jtlucas by Jesse L. */
  JTL_WindowSize WindowSize;

  /** Creates new form Main */
  public Main() {
    GUIUtilities.SetNetBeansCompatibleUIManager();
    initComponents();
    GUIUtilities.setMainWindowLocation( this, null, "GUIMusicCompositionProject" );
    menus = new Menus( this );
    menus.attachMenubar( this );
    WindowSize = new JTL_WindowSize( this );
    WindowSize.setWindowSize( this );
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExit = new javax.swing.JButton();
        jbtnJTLRunMain = new javax.swing.JButton();
        jerronEllipseBtn = new javax.swing.JButton();
        jerronRectBtn = new javax.swing.JButton();
        jerronTriBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnJebertScroll = new javax.swing.JButton();
        jbtnJebertProg = new javax.swing.JButton();
        jbtnPaulOrch = new javax.swing.JButton();
        jetranbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UMass Lowell GUI Programming Music Composition");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jbtnJTLRunMain.setText("JTLucas - Run Main");
        jbtnJTLRunMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJTLRunMainActionPerformed(evt);
            }
        });

        jerronEllipseBtn.setText("Jerron's Ellipse Button");
        jerronEllipseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jerronEllipseBtnActionPerformed(evt);
            }
        });

        jerronRectBtn.setText("Jerron's Rect Button");
        jerronRectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jerronRectBtnActionPerformed(evt);
            }
        });

        jerronTriBtn.setText("Jerron's Tri Button");
        jerronTriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jerronTriBtnActionPerformed(evt);
            }
        });

        jButton1.setText("James Run All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamesButtonActionPerformed(evt);
            }
        });

        jbtnJebertScroll.setText("jebert Scroll");
        jbtnJebertScroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJebertScrollActionPerformed(evt);
            }
        });

        jbtnJebertProg.setText("jebert Progress Bar");
        jbtnJebertProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnJebertProgActionPerformed(evt);
            }
        });

        jbtnPaulOrch.setText("Paul's Instrument Select");
        jbtnPaulOrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaulOrchActionPerformed(evt);
            }
        });

        jetranbutton.setText("Elizabeth's Pic and Colors Button");
        jetranbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jetranbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jerronTriBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jerronRectBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jerronEllipseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jetranbutton)
                            .addComponent(jbtnPaulOrch)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtnJebertProg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnJebertScroll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnJTLRunMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jerronEllipseBtn)
                    .addComponent(jbtnPaulOrch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jerronRectBtn)
                    .addComponent(jetranbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jerronTriBtn)
                .addGap(30, 30, 30)
                .addComponent(jbtnJTLRunMain)
                .addGap(18, 18, 18)
                .addComponent(jbtnJebertScroll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnJebertProg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Event handler called when the main window closes.
 * @param evt standard Java WindowEvent
 */
  private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
    GUIUtilities.saveMainWindowLocation( this, null,
        "GUIMusicCompositionProject", "GUI Music Composition Project" );
  }//GEN-LAST:event_formWindowClosing

/**
 * Event handler for Exit button.
 * @param evt standard Java ActionEvent
 */
  private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    // TODO add your handling code here:
    formWindowClosing( new java.awt.event.WindowEvent( Main.getWindows()[0], 0 ));
    System.exit( 0 );
  }//GEN-LAST:event_btnExitActionPerformed

  /**
   * Button for Ellipse Application.
   * @param evt launch's Jerron's Ellipse sound playing application
   */
  private void jerronEllipseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jerronEllipseBtnActionPerformed
    EllipseSizer_Jer ellipse = new EllipseSizer_Jer(); //create EllipseSizer Object
    String[] args = new String[2]; //probably more logical way around this but it works
    ellipse.main(args); //run main from the EllipseSizer class.
}//GEN-LAST:event_jerronEllipseBtnActionPerformed

   /**
   * Button for Triangle Application.
   * @param evt launch's Jerron's Triangle sound playing application
   */
  private void jerronTriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jerronTriBtnActionPerformed
    TriangleSizer_Jer triangle = new TriangleSizer_Jer(); //create TrianglerSizer object
    String[] args = new String[2];
    triangle.main(args);
  }//GEN-LAST:event_jerronTriBtnActionPerformed

   /**
   * Button for Rectangle Application.
   * @param evt launch's Jerron's Rectangle sound playing application
   */
  private void jerronRectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jerronRectBtnActionPerformed
    Resizing_Jer rect = new Resizing_Jer(); //create Resizing object
    String[] args = new String[2];
    rect.main(args);
  }//GEN-LAST:event_jerronRectBtnActionPerformed

   /**
   * JButton for JTLucas Main Package
   * @param evt launch's JTLucas Main Package
   */
  private void jbtnJTLRunMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJTLRunMainActionPerformed
    //Run my main package
    JTL_WindowSize.main();
  }//GEN-LAST:event_jbtnJTLRunMainActionPerformed

  private void JamesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamesButtonActionPerformed
      // TODO add your handling code here:

      //conflicts with Elizabeth's Resizing, I (Jerron) commented it out so it wouldn't
      //break this main class and emailed James about this issue.
      //Resizing.main(null);
      EllipseSizer.main(null);
      TriangleSizer.main(null);
}//GEN-LAST:event_JamesButtonActionPerformed

  /**
   * Performs jeberts scroll example
   * @param evt a java action event
   */
  private void jbtnJebertScrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJebertScrollActionPerformed
      Scroll.main(null);
  }//GEN-LAST:event_jbtnJebertScrollActionPerformed

  /**
   * goes to jebert's progress bar demo
   * @param evt a java action event
   */
  private void jbtnJebertProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnJebertProgActionPerformed
      PlayFromButtons_Jim.main(null);
  }//GEN-LAST:event_jbtnJebertProgActionPerformed

  /**
   * Starts paul's instrument selection demo
   * @param evt
   */
  private void jbtnPaulOrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaulOrchActionPerformed
      // TODO add your handling code here:
      OrchestraStub.main(null);
}//GEN-LAST:event_jbtnPaulOrchActionPerformed

  private void jetranbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jetranbuttonActionPerformed
      // TODO add your handling code here:
      PicNColors.main(null);
  }//GEN-LAST:event_jetranbuttonActionPerformed

  /**
   * This is the public version of the private NetBeans-generated btnExitActionPerformed
   * that can be called from other classes.
   */
  public void btnExitActionPerformed() {
    btnExitActionPerformed( null ) ;
  }

  /**
   * The standard Java main method.
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new Main().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    /** Exit button on the main window */
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    /* This button will activate the main in the JTLucas Package */
    private javax.swing.JButton jbtnJTLRunMain;
    private javax.swing.JButton jbtnJebertProg;
    private javax.swing.JButton jbtnJebertScroll;
    private javax.swing.JButton jbtnPaulOrch;
    private javax.swing.JButton jerronEllipseBtn;
    private javax.swing.JButton jerronRectBtn;
    private javax.swing.JButton jerronTriBtn;
    private javax.swing.JButton jetranbutton;
    // End of variables declaration//GEN-END:variables
}
